DesperadoUnmannedGearGekko=Беспилотный Механический «Гекко» ООО «Безопасность Десперадо»
WorldMarshalUnmannedGearGekko=Беспилотный Механический «Гекко» ЧВК «Мировой Маршал»

Caption_Gekko/Taunt/1.wav=МУУ!
Caption_Gekko/Taunt/2.wav=МУУ!
Caption_Gekko/Taunt/3.wav=МУУ!

DesperadoDwarfGekko=Карликовый «Гекко» ООО «Безопасность Десперадо»