WorldMarshal=World Marshal
DesperadoEnforcementLLC=Desperado Enforcement LLC

DesperadoUnmannedGearIRVING=Desperado Enforcement LLC Unmanned Gear IRVING
WorldMarshalUnmannedGearIRVING=World Marshal Unmanned Gear IRVING

DesperadoDwarfGekko=Desperado Enforcement LLC Unmanned Gear Tripod

DesperadoUnmannedGearGRAD=(WiP) Desperado Enforcement LLC Unmanned Gear GRAD
WorldMarshalUnmannedGearGRAD=(WiP) World Marshal Unmanned Gear GRAD
