WorldMarshal=World Marshal
DesperadoEnforcementLLC=Desperado Enforcement LLC

DesperadoUnmannedGearIRVING=Desperado Enforcement LLC Unmanned Gear IRVING
WorldMarshalUnmannedGearIRVING=World Marshal Unmanned Gear IRVING

DesperadoUnmannedGearScarab=Desperado Enforcement LLC Unmanned Gear Scarab

DesperadoUnmannedGearGRAD=(WiP) Desperado Enforcement LLC Unmanned Gear GRAD
WorldMarshalUnmannedGearGRAD=(WiP) World Marshal Unmanned Gear GRAD
