DesperadoUnmannedGearGekko=Desperado Enforcement LLC Unmanned Gear Gekko
WorldMarshalUnmannedGearGekko=PMC World Marshal Unmanned Gear Gekko

Caption_Gekko/Taunt/1.wav=MOO!
Caption_Gekko/Taunt/2.wav=MOO!
Caption_Gekko/Taunt/3.wav=MOO!

DesperadoDwarfGekko=Desperado Dwarf Gekko